//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObajuShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string userId { get; set; }
        public System.DateTime orderDate { get; set; }
        public string orderTrackingNumber { get; set; }
        public bool status { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
