//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObajuShopping.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ObajuEntities : DbContext
    {
        public ObajuEntities()
            : base("name=ObajuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Product { get; set; }
    
        public virtual ObjectResult<list_products_reg_Result> list_products_reg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<list_products_reg_Result>("list_products_reg");
        }
    }
}
